export const ADD_TO_APOINTMENT = "ADD_TO_APPOINTMENT";

export const REMOVE_APPOINTMENT_DOCTOR = "REMOVE_APPOINTMENT_DOCTOR";

export const SAVE_ANIMAL_INFO = "SAVE_ANIMAL_INFO";

export const SAVE_APPOINTMENT_DATE = "SAVE_APPOINTMENT_DATE";