export const LOGIN_REQUEST_DOCTOR="LOGIN_REQUEST_DOCTOR";

export const LOGIN_SUCCESS_DOCTOR="LOGIN_SUCCESS_DOCTOR";

export const LOGIN_FAIL_DOCTOR="LOGIN_FAIL_DOCTOR";


export const REGISTER_DOCTOR_REQUEST="REGISTER_DOCTOR_REQUEST";

export const REGISTER_DOCTOR_SUCCESS="REGISTER_DOCTOR_SUCCESS";

export const REGISTER_DOCTOR_FAIL="REGISTER_DOCTOR_FAIL";


export const LOAD_DOCTOR_REQUEST="LOAD_DOCTOR_REQUEST";
 
export const LOAD_DOCTOR_SUCCESS="LOAD_DOCTOR_SUCCESS";

export const LOAD_DOCTOR_FAIL="LOAD_DOCTOR_FAIL";


export const LOGOUT_SUCCESS_DOCTOR="LOGOUT_SUCCESS";

export const LOGOUT_FAIL_DOCTOR="LOGOUT_FAIL_DOCTOR";


export const UPDATE_PASSWORD_REQUEST="UPDATE_PASSWORD_REQUEST";
 
export const UPDATE_PASSWORD_SUCCESS="UPDATE_PASSWORD_SUCCESS";

export const UPDATE_PASSWORD_RESET="UPDATE_PASSWORD_RESET";

export const UPDATE_PASSWORD_FAIL="UPDATE_PASSWORD_FAIL";


export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const ALL_DOCTORS_REQUEST = "ALL_DOCTORS_REQUEST";
export const ALL_DOCTORS_SUCCESS = "ALL_DOCTORS_SUCCESS";
export const ALL_DOCTORS_FAIL = "ALL_DOCTORS_FAIL";

export const DOCTOR_DETAILS_REQUEST = "DOCTOR_DETAILS_REQUEST";
export const DOCTOR_DETAILS_SUCCESS = "DOCTOR_DETAILS_SUCCESS";
export const DOCTOR_DETAILS_FAIL = "DOCTOR_DETAILS_FAIL";

export const ADMIN_DOCTOR_REQUEST = "ADMIN_DOCTOR_REQUEST";
export const ADMIN_DOCTOR_SUCCESS = "ADMIN_DOCTOR_SUCCESS";
export const ADMIN_DOCTOR_FAIL = "ADMIN_DOCTOR_FAIL";


export const UPDATE_DOCTOR_REQUEST = "UPDATE_DOCTOR_REQUEST";
export const UPDATE_DOCTOR_SUCCESS = "UPDATE_DOCTOR_SUCCESS";
export const UPDATE_DOCTOR_RESET = "UPDATE_DOCTOR_RESET";
export const UPDATE_DOCTOR_FAIL = "UPDATE_DOCTOR_FAIL";

export const DELETE_DOCTOR_REQUEST = "DELETE_DOCTOR_REQUEST";
export const DELETE_DOCTOR_SUCCESS = "DELETE_DOCTOR_SUCCESS";
export const DELETE_DOCTOR_FAIL = "DELETE_DOCTOR_FAIL";
export const DELETE_DOCTOR_RESET = "DELETE_DOCTOR_RESET";

export const NEW_DOCTOR_REQUEST = "NEW_DOCTOR_REQUEST";
export const NEW_DOCTOR_SUCCESS = "NEW_DOCTOR_SUCCESS";
export const NEW_DOCTOR_RESET = "NEW_DOCTOR_RESET";
export const NEW_DOCTOR_FAIL = "NEW_DOCTOR_FAIL";


export const CLEAR_ERRORS="CLEAR_ERRORS";