export const ALL_MEDICINE_REQUEST = "ALL_MEDICINE_REQUEST";
export const ALL_MEDICINE_SUCCESS = "ALL_MEDICINE_SUCCESS";
export const ALL_MEDICINE_FAIL = "ALL_MEDICINE_FAIL";

export const ADMIN_MEDICINE_REQUEST = "ADMIN_MEDICINE_REQUEST";
export const ADMIN_MEDICINE_SUCCESS = "ADMIN_MEDICINE_SUCCESS";
export const ADMIN_MEDICINE_FAIL = "ADMIN_MEDICINE_FAIL";

export const NEW_MEDICINE_REQUEST = "NEW_MEDICINE_REQUEST";
export const NEW_MEDICINE_SUCCESS = "NEW_MEDICINE_SUCCESS";
export const NEW_MEDICINE_RESET = "NEW_MEDICINE_RESET";
export const NEW_MEDICINE_FAIL = "NEW_MEDICINE_FAIL";

export const UPDATE_MEDICINE_REQUEST = "UPDATE_MEDICINE_REQUEST";
export const UPDATE_MEDICINE_SUCCESS = "UPDATE_MEDICINE_SUCCESS";
export const UPDATE_MEDICINE_RESET = "UPDATE_MEDICINE_RESET";
export const UPDATE_MEDICINE_FAIL = "UPDATE_MEDICINE_FAIL";

export const DELETE_MEDICINE_REQUEST = "DELETE_MEDICINE_REQUEST";
export const DELETE_MEDICINE_SUCCESS = "DELETE_MEDICINE_SUCCESS";
export const DELETE_MEDICINE_RESET = "DELETE_MEDICINE_RESET";
export const DELETE_MEDICINE_FAIL = "DELETE_MEDICINE_FAIL";

export const MEDICINE_DETAILS_REQUEST = "MEDICINE_DETAILS_REQUEST";
export const MEDICINE_DETAILS_SUCCESS = "MEDICINE_DETAILS_SUCCESS";
export const MEDICINE_DETAILS_FAIL = "MEDICINE_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";